<?php
require __DIR__ . '/bootstrap.php';
$root = dirname(__DIR__);
$commerce = file_get_contents($root . '/includes/class-mkt-commerce.php');
$moderation = file_get_contents($root . '/includes/class-mkt-moderation.php');
$events = file_get_contents($root . '/includes/class-mkt-events.php');
$integration = file_get_contents($root . '/includes/class-mkt-integrations.php');
$rest_security = file_get_contents($root . '/includes/class-mkt-rest-security.php');
$plugin = file_get_contents($root . '/marketplace.php');
$rest = file_get_contents($root . '/includes/class-mkt-rest.php');
$idempotency = file_get_contents($root . '/includes/class-mkt-idempotency.php');
$admin = file_get_contents($root . '/includes/class-mkt-admin.php');
$privacy = file_get_contents($root . '/includes/class-mkt-privacy.php');
$audit = file_get_contents($root . '/includes/class-mkt-audit.php');
$css = file_get_contents($root . '/assets/css/marketplace.css');
$js = file_get_contents($root . '/assets/js/marketplace.js');
$db = file_get_contents($root . '/includes/class-mkt-db.php');

assert_true(str_contains($rest, 'MKT_Idempotency::run'), 'REST mutations are replay-protected.');
assert_true(str_contains($js, "headers['Idempotency-Key']"), 'Browser mutations emit idempotency keys.');
assert_true(str_contains($rest_security, "did_action('application_password_did_authenticate')") && str_contains($rest_security, "get_header('X-WP-Nonce')") && str_contains($rest_security, "wp_verify_nonce"), 'REST mutation CSRF guard trusts successful Application Password authentication, not arbitrary Authorization-header presence.');
assert_true(str_contains($plugin, "'class-mkt-rest-security.php'") && str_contains($plugin, "['MKT_REST_Security','boot']"), 'Strict REST mutation CSRF guard is loaded and booted.');
assert_true(str_contains($idempotency, 'request_hash') && str_contains($idempotency, 'mkt_idempotency_conflict'), 'Idempotency key reuse with altered payload is rejected.');
assert_true(str_contains($commerce, "SELECT l.*,s.public_id") && str_contains($commerce, 'FOR UPDATE'), 'Offer acceptance locks listing and rechecks seller state.');
assert_true(substr_count($commerce, 'FOR UPDATE') >= 3 && str_contains($commerce, 'fresh_listing') && substr_count($commerce, 'MKT_Auth::seller_eligibility') >= 2, 'Offer and counter creation re-lock canonical listing state and revalidate current seller eligibility.');
assert_true(substr_count($commerce, 'MKT_Auth::seller_eligibility') >= 3 && str_contains($commerce, 'no longer eligible to enter a marketplace deal'), 'Deal commitment revalidates authoritative seller eligibility after the listing lock.');
assert_true(str_contains($commerce, "listing_status === 'sold_unavailable'"), 'Sold-out acceptance closes every competing live offer.');
assert_true(str_contains($commerce, 'mkt_deal_reviewer_scope'), 'Reviewer access is restricted to disputed/resolved deals.');
assert_true(str_contains($commerce, 'mkt_dispute_record_required'), 'Deal dispute state requires a structured dispute record.');
assert_true(str_contains($moderation, "'non_delivery'") && str_contains($moderation, "'impersonation'") && str_contains($moderation, "'child_safety'"), 'Canonical moderation API preserves the complete safety-report taxonomy.');
assert_true(str_contains($moderation, '$listing_result = MKT_Listings::transition') && str_contains($moderation, 'if (is_wp_error($listing_result))'), 'Listing restriction failures propagate so the owner transaction can roll back the report state.');
assert_true(str_contains($events, '$paused === false') && str_contains($events, 'mkt_seller_listing_pause_failed'), 'Seller-suspension reconciliation does not acknowledge an event when active listings fail to pause.');
assert_true(str_contains($events, '$listing_exists') && str_contains($events, 'mkt_communication_report_write_failed'), 'File 17 report events validate their Marketplace target and remain retryable when report persistence fails.');
assert_true(str_contains($integration, 'MKT_Auth::seller_eligibility($other_user_id)') && str_contains($integration, 'mkt_seller_contact_unavailable'), 'File 17 Marketplace handoff revalidates current seller eligibility.');
assert_true(str_contains($integration, 'wp_parse_url(home_url') && str_contains($integration, 'mkt_communication_url_invalid'), 'File 17 conversation handoff is constrained to a same-origin destination.');
assert_true(str_contains($admin, "current_user_can('mkt_moderate')") && str_contains($admin, "current_user_can('mkt_review_disputes')"), 'Moderation UI follows least privilege.');
assert_true(str_contains($privacy, "'dispute' => \$wpdb->get_results") && str_contains($privacy, "MKT_DB::table('disputes')") && str_contains($privacy, "'group_id' => 'mkt-' . \$type"), 'Privacy export includes participant disputes through the generic bounded exporter.');
assert_true(str_contains($privacy, 'private const EXPORT_BATCH = 100') && str_contains($privacy, 'private const ERASE_BATCH = 100'), 'Privacy export and erasure are bounded.');
assert_true(str_contains($audit, 'GET_LOCK') && str_contains($audit, 'verify_chain'), 'Audit chain has concurrency control and verification.');
assert_true(str_contains($audit, 'if (!$inserted)') && str_contains($audit, 'audit evidence could not be persisted'), 'Required audit evidence cannot fail silently.');
assert_true(!str_contains($css, '.mkt-button-small{min-height:36px') && str_contains($css, '.mkt-button-small{min-height:44px') && str_contains($css, '.mkt-tabs button{min-height:44px'), 'Interactive Marketplace controls preserve the central 44px minimum touch target.');
assert_true(!preg_match('/\bmkt_(conversations?|messages?|calls?|wallets?|escrows?|payouts?)\b/i', $db), 'No parallel communication or money canonical table exists.');
fwrite(STDOUT, "Adversarial invariant suite complete.\n");
