<?php
defined('ABSPATH') || exit;
require MKT_DIR . 'templates/_header.php';
$data = MKT_Commerce::dashboard(get_current_user_id());
$user_id = (int) $data['current_user_id'];
?>
<section class="mkt-dashboard"><header><p class="mkt-eyebrow"><?php esc_html_e('Private workspace', 'marketplace'); ?></p><h1><?php esc_html_e('Marketplace dashboard', 'marketplace'); ?></h1><p><?php esc_html_e('Manage your listings, offers, direct deals and safety cases. This page is private, noindex and no-cache.', 'marketplace'); ?></p></header>
<div class="mkt-dashboard-stats"><div><strong><?php echo esc_html((string) count($data['listings'])); ?></strong><span><?php esc_html_e('Listings', 'marketplace'); ?></span></div><div><strong><?php echo esc_html((string) count($data['offers'])); ?></strong><span><?php esc_html_e('Offers', 'marketplace'); ?></span></div><div><strong><?php echo esc_html((string) count($data['deals'])); ?></strong><span><?php esc_html_e('Deals', 'marketplace'); ?></span></div><div><strong>0%</strong><span><?php esc_html_e('Commission', 'marketplace'); ?></span></div></div>
<div class="mkt-form-actions"><a class="mkt-button mkt-button-primary" href="<?php echo esc_url(home_url('/marketplace/sell/')); ?>">＋ <?php esc_html_e('Create listing', 'marketplace'); ?></a><a class="mkt-button mkt-button-secondary" href="<?php echo esc_url(home_url('/marketplace/')); ?>"><?php esc_html_e('Browse marketplace', 'marketplace'); ?></a></div>
<div class="mkt-tabs" role="tablist"><button role="tab" aria-selected="true" data-mkt-tab="listings"><?php esc_html_e('Listings', 'marketplace'); ?></button><button role="tab" aria-selected="false" data-mkt-tab="offers"><?php esc_html_e('Offers', 'marketplace'); ?></button><button role="tab" aria-selected="false" data-mkt-tab="deals"><?php esc_html_e('Deals', 'marketplace'); ?></button><button role="tab" aria-selected="false" data-mkt-tab="safety"><?php esc_html_e('Reports & disputes', 'marketplace'); ?></button></div>

<section data-mkt-panel="listings"><h2><?php esc_html_e('Your listings', 'marketplace'); ?></h2><?php if (!$data['listings']): ?><div class="mkt-empty"><p><?php esc_html_e('No listings yet.', 'marketplace'); ?></p></div><?php else: ?><div class="mkt-table-wrap"><table class="mkt-table"><thead><tr><th><?php esc_html_e('Listing', 'marketplace'); ?></th><th><?php esc_html_e('Price', 'marketplace'); ?></th><th><?php esc_html_e('Status', 'marketplace'); ?></th><th><?php esc_html_e('Updated', 'marketplace'); ?></th><th><?php esc_html_e('Actions', 'marketplace'); ?></th></tr></thead><tbody>
<?php foreach ($data['listings'] as $item): ?><tr data-mkt-listing-row data-listing-id="<?php echo esc_attr((string) $item['public_id']); ?>" data-listing-version="<?php echo esc_attr((string) $item['version']); ?>"><td><a href="<?php echo esc_url($item['url']); ?>"><?php echo esc_html((string) $item['title']); ?></a></td><td><bdi><?php echo esc_html((string) $item['currency'] . ' ' . (string) $item['price']); ?></bdi></td><td><span class="mkt-status" data-status="<?php echo esc_attr((string) $item['status']); ?>"><?php echo esc_html(ucwords(str_replace('_',' ',(string) $item['status']))); ?></span></td><td><?php echo esc_html(mysql2date(get_option('date_format'), (string) $item['updated_at'])); ?></td><td><div class="mkt-inline-actions"><?php if (in_array((string) $item['status'], ['draft','paused','rejected','appealed'], true)): ?><a class="mkt-button mkt-button-secondary" href="<?php echo esc_url(add_query_arg(['id' => $item['public_id']], home_url('/marketplace/sell/'))); ?>"><?php esc_html_e('Edit', 'marketplace'); ?></a><?php endif; ?><?php if ((string) $item['status'] === 'active'): ?><button class="mkt-button mkt-button-secondary" data-mkt-listing-action="paused"><?php esc_html_e('Pause', 'marketplace'); ?></button><button class="mkt-button mkt-button-secondary" data-mkt-listing-action="sold_unavailable"><?php esc_html_e('Mark sold', 'marketplace'); ?></button><?php elseif ((string) $item['status'] === 'paused'): ?><button class="mkt-button mkt-button-secondary" data-mkt-listing-action="active"><?php esc_html_e('Reactivate', 'marketplace'); ?></button><?php elseif (in_array((string) $item['status'], ['rejected','removed'], true)): ?><button class="mkt-button mkt-button-secondary" data-mkt-listing-action="appealed"><?php esc_html_e('Appeal', 'marketplace'); ?></button><?php endif; ?></div></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>

<section hidden data-mkt-panel="offers"><h2><?php esc_html_e('Offers', 'marketplace'); ?></h2><?php if (!$data['offers']): ?><div class="mkt-empty"><p><?php esc_html_e('No offers yet.', 'marketplace'); ?></p></div><?php else: ?><div class="mkt-table-wrap"><table class="mkt-table"><thead><tr><th><?php esc_html_e('Listing', 'marketplace'); ?></th><th><?php esc_html_e('Amount', 'marketplace'); ?></th><th><?php esc_html_e('Status', 'marketplace'); ?></th><th><?php esc_html_e('Expires', 'marketplace'); ?></th><th><?php esc_html_e('Actions', 'marketplace'); ?></th></tr></thead><tbody>
<?php foreach ($data['offers'] as $offer): $creator = (int) $offer['created_by'] === $user_id; $participant = in_array($user_id, [(int) $offer['buyer_user_id'], (int) $offer['seller_user_id']], true); ?><tr data-mkt-offer-row data-offer-id="<?php echo esc_attr((string) $offer['public_id']); ?>" data-offer-version="<?php echo esc_attr((string) $offer['version']); ?>"><td><?php echo esc_html((string) ($offer['listing_title'] ?: substr((string) $offer['listing_public_id'],0,8))); ?></td><td><bdi><?php echo esc_html((string) $offer['currency'] . ' ' . (string) $offer['amount']); ?></bdi></td><td><span class="mkt-status" data-status="<?php echo esc_attr((string) $offer['status']); ?>"><?php echo esc_html(ucwords(str_replace('_',' ',(string) $offer['status']))); ?></span></td><td><?php echo esc_html(mysql2date(get_option('date_format'), (string) $offer['expires_at'])); ?></td><td><div class="mkt-inline-actions"><?php if ($participant && in_array((string) $offer['status'], ['open','countered'], true)): ?><?php if ($creator): ?><button class="mkt-button mkt-button-secondary" data-mkt-offer-action="withdrawn"><?php esc_html_e('Withdraw', 'marketplace'); ?></button><?php else: ?><button class="mkt-button mkt-button-primary" data-mkt-offer-action="accepted"><?php esc_html_e('Accept', 'marketplace'); ?></button><button class="mkt-button mkt-button-secondary" data-mkt-offer-action="declined"><?php esc_html_e('Decline', 'marketplace'); ?></button><?php endif; ?><button class="mkt-button mkt-button-secondary" data-mkt-offer-action="countered"><?php esc_html_e('Counter', 'marketplace'); ?></button><?php endif; ?></div></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>

<section hidden data-mkt-panel="deals"><h2><?php esc_html_e('Deals', 'marketplace'); ?></h2><?php if (!$data['deals']): ?><div class="mkt-empty"><p><?php esc_html_e('No deals yet.', 'marketplace'); ?></p></div><?php else: ?><div class="mkt-table-wrap"><table class="mkt-table"><thead><tr><th><?php esc_html_e('Listing', 'marketplace'); ?></th><th><?php esc_html_e('Agreed amount', 'marketplace'); ?></th><th><?php esc_html_e('Status', 'marketplace'); ?></th><th><?php esc_html_e('Updated', 'marketplace'); ?></th><th></th></tr></thead><tbody><?php foreach ($data['deals'] as $deal): ?><tr><td><?php echo esc_html((string) ($deal['listing_title'] ?: substr((string) $deal['listing_public_id'],0,8))); ?></td><td><bdi><?php echo esc_html((string) $deal['currency'] . ' ' . (string) $deal['agreed_amount']); ?></bdi></td><td><span class="mkt-status" data-status="<?php echo esc_attr((string) $deal['status']); ?>"><?php echo esc_html(ucwords(str_replace('_',' ',(string) $deal['status']))); ?></span></td><td><?php echo esc_html(mysql2date(get_option('date_format'), (string) $deal['updated_at'])); ?></td><td><a class="mkt-button mkt-button-secondary" href="<?php echo esc_url($deal['url']); ?>"><?php esc_html_e('Open deal', 'marketplace'); ?></a></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>

<section hidden data-mkt-panel="safety"><h2><?php esc_html_e('Your reports', 'marketplace'); ?></h2><?php if (!$data['reports']): ?><p><?php esc_html_e('No reports submitted.', 'marketplace'); ?></p><?php else: ?><div class="mkt-table-wrap"><table class="mkt-table"><thead><tr><th>ID</th><th><?php esc_html_e('Target', 'marketplace'); ?></th><th><?php esc_html_e('Reason', 'marketplace'); ?></th><th><?php esc_html_e('Status', 'marketplace'); ?></th><th><?php esc_html_e('Action', 'marketplace'); ?></th></tr></thead><tbody><?php foreach ($data['reports'] as $report): ?><tr data-mkt-report-row data-report-id="<?php echo esc_attr((string) $report['public_id']); ?>" data-report-version="<?php echo esc_attr((string) $report['version']); ?>"><td><code><?php echo esc_html(substr((string) $report['public_id'],0,8)); ?></code></td><td><?php echo esc_html((string) $report['target_type']); ?></td><td><?php echo esc_html((string) $report['reason']); ?></td><td><span class="mkt-status"><?php echo esc_html((string) $report['status']); ?></span></td><td><?php if (in_array((string) $report['status'], ['restricted','no_action','decided'], true)): ?><button class="mkt-button mkt-button-secondary" data-mkt-report-appeal><?php esc_html_e('Appeal', 'marketplace'); ?></button><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
<h2><?php esc_html_e('Your disputes', 'marketplace'); ?></h2><?php if (!$data['disputes']): ?><p><?php esc_html_e('No disputes.', 'marketplace'); ?></p><?php else: ?><div class="mkt-table-wrap"><table class="mkt-table"><thead><tr><th>ID</th><th><?php esc_html_e('Reason', 'marketplace'); ?></th><th><?php esc_html_e('Status', 'marketplace'); ?></th><th><?php esc_html_e('Action', 'marketplace'); ?></th></tr></thead><tbody><?php foreach ($data['disputes'] as $dispute): ?><tr data-mkt-dispute-row data-dispute-id="<?php echo esc_attr((string) $dispute['public_id']); ?>" data-dispute-version="<?php echo esc_attr((string) $dispute['version']); ?>"><td><a href="<?php echo esc_url(home_url('/marketplace/deal/' . rawurlencode((string) $dispute['deal_public_id']) . '/')); ?>"><code><?php echo esc_html(substr((string) $dispute['public_id'],0,8)); ?></code></a></td><td><?php echo esc_html((string) $dispute['reason']); ?></td><td><span class="mkt-status"><?php echo esc_html((string) $dispute['status']); ?></span></td><td><?php if ((string) $dispute['status'] === 'decided'): ?><button class="mkt-button mkt-button-secondary" data-mkt-dispute-action="appealed"><?php esc_html_e('Appeal', 'marketplace'); ?></button><?php elseif (in_array((string) $dispute['status'], ['opened','evidence'], true)): ?><button class="mkt-button mkt-button-secondary" data-mkt-dispute-action="withdrawn"><?php esc_html_e('Withdraw', 'marketplace'); ?></button><?php elseif ((string) $dispute['status'] === 'more_info'): ?><button class="mkt-button mkt-button-secondary" data-mkt-dispute-action="evidence"><?php esc_html_e('Submit more information', 'marketplace'); ?></button><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
</section><div class="mkt-toast" hidden role="status" aria-live="polite" data-mkt-toast></div>
<?php require MKT_DIR . 'templates/_footer.php'; ?>
