<?php
defined('ABSPATH') || exit;
require MKT_DIR . 'templates/_header.php';
$public_id=(string)get_query_var('mkt_object_id');
$listing=MKT_Listings::get($public_id,false);
$recall=class_exists('MKT_Governance') ? MKT_Governance::public_recall($public_id) : null;
// A recall activation intentionally pauses an active listing. Keep a narrowly
// scoped public safety notice reachable for that exact recalled object without
// re-exposing arbitrary drafts/paused/private listings.
if (!$listing && $recall) $listing=MKT_Listings::get($public_id,true);
if (!$listing) { status_header(404); ?>
<section class="mkt-empty"><span aria-hidden="true">!</span><h1><?php esc_html_e('Listing unavailable','marketplace'); ?></h1><p><?php esc_html_e('The listing may have expired, been removed, or no longer be publicly eligible.','marketplace'); ?></p><a class="mkt-button mkt-button-primary" href="<?php echo esc_url(home_url('/marketplace/')); ?>"><?php esc_html_e('Return to Marketplace','marketplace'); ?></a></section>
<?php require MKT_DIR.'templates/_footer.php'; return; }
$item=MKT_Listings::public_dto($listing);
$language=MKT_Finalization::listing_language((int)$listing['id']);
$evidence=class_exists('MKT_Governance') ? MKT_Governance::public_evidence((string)$item['public_id']) : null;
?>
<article class="mkt-listing-detail" data-listing-id="<?php echo esc_attr($item['public_id']); ?>">
  <div class="mkt-gallery" aria-label="<?php esc_attr_e('Listing media','marketplace'); ?>"><?php if (!$item['media']): ?><div class="mkt-gallery-empty" aria-hidden="true">▧</div><?php endif; ?><?php foreach ($item['media'] as $media): $url=$media['metadata']['url'] ?? $media['metadata']['thumbnail_url'] ?? ''; if (!$url) continue; ?><figure><img src="<?php echo esc_url((string)$url); ?>" alt="<?php echo esc_attr((string)$media['alt_text']); ?>" loading="lazy"></figure><?php endforeach; ?></div>
  <div class="mkt-detail-panel">
    <p class="mkt-eyebrow"><?php echo esc_html(ucwords(str_replace('_',' ',(string)$item['category']))); ?><?php if ($language && $language!=='und'): ?> · <?php echo esc_html(strtoupper($language)); ?><?php endif; ?></p>
    <h1><?php echo esc_html((string)$item['title']); ?></h1>
    <?php if ($recall): ?><div class="mkt-alert mkt-alert-error" role="alert"><h2><?php esc_html_e('Recall / takedown notice','marketplace'); ?></h2><p><?php echo esc_html((string)$recall['reason']); ?><?php if (!empty($recall['batch_ref'])): ?> — <?php echo esc_html(sprintf(__('Batch/reference: %s','marketplace'),(string)$recall['batch_ref'])); ?><?php endif; ?></p><?php if (!empty($recall['regulator_reference'])): ?><p><?php echo esc_html(sprintf(__('Regulatory reference: %s','marketplace'),(string)$recall['regulator_reference'])); ?></p><?php endif; ?><p><?php esc_html_e('Offers and seller-contact actions are disabled while this safety notice is active.','marketplace'); ?></p></div><?php endif; ?>
    <p class="mkt-price mkt-price-large"><bdi><?php echo esc_html((string)$item['currency'].' '.(string)$item['price']); ?></bdi></p>
    <div class="mkt-trust-strip"><?php if ($recall): ?><span>⚠ <?php esc_html_e('Safety notice active','marketplace'); ?></span><?php else: ?><span>✓ <?php esc_html_e('Approved listing','marketplace'); ?></span><?php endif; ?><span>0% <?php esc_html_e('platform commission','marketplace'); ?></span><span>↻ <?php echo esc_html(sprintf(__('Updated %s','marketplace'),mysql2date(get_option('date_format'),(string)$item['updated_at']))); ?></span></div>
    <div class="mkt-description"><?php echo wp_kses_post(wpautop((string)$item['description'])); ?></div>
    <dl class="mkt-facts"><div><dt><?php esc_html_e('Seller','marketplace'); ?></dt><dd><?php echo esc_html((string)$item['seller']['store_name']); ?></dd></div><div><dt><?php esc_html_e('Condition','marketplace'); ?></dt><dd><?php echo esc_html(ucwords(str_replace('_',' ',(string)$item['condition_name']))); ?></dd></div><div><dt><?php esc_html_e('Location','marketplace'); ?></dt><dd><?php echo esc_html(trim(implode(', ',array_filter([(string)$item['location_city'],(string)$item['location_region'],(string)$item['location_country']])))); ?></dd></div><div><dt><?php esc_html_e('Availability','marketplace'); ?></dt><dd><?php echo esc_html(ucwords(str_replace('_',' ',(string)$item['availability']))); ?></dd></div><?php if ($language && $language!=='und'): ?><div><dt><?php esc_html_e('Language','marketplace'); ?></dt><dd><?php echo esc_html($language); ?></dd></div><?php endif; ?></dl>
    <?php if ($evidence): ?><section class="mkt-safety-note" aria-labelledby="mkt-evidence-public"><h2 id="mkt-evidence-public"><?php esc_html_e('Reviewed product evidence','marketplace'); ?></h2><dl class="mkt-facts"><?php if ($evidence['ingredients']): ?><div><dt><?php esc_html_e('Ingredients / constituents','marketplace'); ?></dt><dd><?php echo esc_html(implode(', ',(array)$evidence['ingredients'])); ?></dd></div><?php endif; ?><div><dt><?php esc_html_e('Manufacturer','marketplace'); ?></dt><dd><?php echo esc_html((string)$evidence['manufacturer']); ?></dd></div><?php foreach (['license_or_registration'=>__('License / registration','marketplace'),'batch_number'=>__('Batch','marketplace'),'expiry_date'=>__('Expiry','marketplace')] as $key=>$label): ?><div><dt><?php echo esc_html($label); ?></dt><dd><?php echo esc_html((string)($evidence[$key] ?: ($evidence['not_applicable'][$key] ?? __('Not applicable','marketplace')))); ?></dd></div><?php endforeach; ?></dl><?php if (!empty($evidence['source_refs'])): ?><p><strong><?php esc_html_e('Evidence references:','marketplace'); ?></strong> <?php echo esc_html(implode(' · ',(array)$evidence['source_refs'])); ?></p><?php endif; ?><p><?php esc_html_e('Evidence review does not constitute a cure guarantee or platform endorsement of a treatment outcome.','marketplace'); ?></p></section><?php endif; ?>
    <div class="mkt-actions"><?php if (!$recall && is_user_logged_in()): ?><button class="mkt-button mkt-button-primary" type="button" data-mkt-chat>◉ <?php esc_html_e('Message seller','marketplace'); ?></button><button class="mkt-button mkt-button-secondary" type="button" data-mkt-offer>¤ <?php esc_html_e('Make an offer','marketplace'); ?></button><button class="mkt-button mkt-button-quiet" type="button" data-mkt-save>♡ <?php esc_html_e('Save','marketplace'); ?></button><?php elseif (!$recall): ?><a class="mkt-button mkt-button-primary" href="<?php echo esc_url(wp_login_url($item['url'])); ?>"><?php esc_html_e('Sign in to contact seller','marketplace'); ?></a><?php endif; ?><?php if (is_user_logged_in()): ?><button class="mkt-button mkt-button-quiet" type="button" data-mkt-report>⚑ <?php esc_html_e('Report','marketplace'); ?></button><?php endif; ?><button class="mkt-button mkt-button-quiet" type="button" data-mkt-share data-share-url="<?php echo esc_url($item['url']); ?>">⇧ <?php esc_html_e('Share','marketplace'); ?></button></div>
    <aside class="mkt-safety-note"><h2><?php esc_html_e('Transaction safety','marketplace'); ?></h2><p><?php esc_html_e('Marketplace records offers and deal status but does not guarantee payment, delivery, authenticity or medical outcomes. Verify the seller and product before paying. Do not share patient records.','marketplace'); ?></p></aside>
  </div>
</article>
<?php if (!$recall): ?><div class="mkt-modal" hidden data-mkt-offer-modal role="dialog" aria-modal="true" aria-labelledby="mkt-offer-title"><div class="mkt-modal-panel"><button class="mkt-modal-close" type="button" data-mkt-close aria-label="<?php esc_attr_e('Close','marketplace'); ?>">×</button><h2 id="mkt-offer-title"><?php esc_html_e('Make an offer','marketplace'); ?></h2><form data-mkt-offer-form><label><span><?php esc_html_e('Amount','marketplace'); ?></span><input required type="number" min="0.01" step="0.01" name="amount"></label><label><span><?php esc_html_e('Currency','marketplace'); ?></span><input required maxlength="3" name="currency" value="<?php echo esc_attr((string)$item['currency']); ?>"></label><label><span><?php esc_html_e('Terms','marketplace'); ?></span><textarea name="terms" rows="4"></textarea></label><button class="mkt-button mkt-button-primary" type="submit"><?php esc_html_e('Submit structured offer','marketplace'); ?></button></form></div></div><?php endif; ?>
<div class="mkt-modal" hidden data-mkt-report-modal role="dialog" aria-modal="true" aria-labelledby="mkt-report-title"><div class="mkt-modal-panel"><button class="mkt-modal-close" type="button" data-mkt-close aria-label="<?php esc_attr_e('Close','marketplace'); ?>">×</button><h2 id="mkt-report-title"><?php esc_html_e('Report listing','marketplace'); ?></h2><form data-mkt-report-form><label><span><?php esc_html_e('Reason','marketplace'); ?></span><select name="reason"><?php foreach (['fraud'=>__('Fraud','marketplace'),'scam'=>__('Scam','marketplace'),'counterfeit'=>__('Counterfeit','marketplace'),'non_delivery'=>__('Non-delivery','marketplace'),'unsafe'=>__('Unsafe product','marketplace'),'unsafe_claim'=>__('Unsafe claim','marketplace'),'false_claim'=>__('False claim','marketplace'),'false_cure_claim'=>__('False cure claim','marketplace'),'impersonation'=>__('Impersonation','marketplace'),'privacy'=>__('Privacy violation','marketplace'),'harassment'=>__('Harassment','marketplace'),'abuse'=>__('Abuse','marketplace'),'copyright'=>__('Copyright / rights','marketplace'),'child_safety'=>__('Child safety','marketplace'),'illegal'=>__('Illegal item or service','marketplace'),'misleading_price'=>__('Misleading price','marketplace'),'other'=>__('Other','marketplace')] as $key=>$label): ?><option value="<?php echo esc_attr($key); ?>"><?php echo esc_html($label); ?></option><?php endforeach; ?></select></label><label><span><?php esc_html_e('Details','marketplace'); ?></span><textarea required minlength="10" name="details" rows="5"></textarea></label><button class="mkt-button mkt-button-primary" type="submit"><?php esc_html_e('Submit report','marketplace'); ?></button></form></div></div>
<div class="mkt-toast" hidden role="status" aria-live="polite" data-mkt-toast></div>
<?php require MKT_DIR.'templates/_footer.php'; ?>
